### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by yutannihilation** [yutannihilation/kokudosuuchi-metadata#1]
- [ ] `A03`のコードリスト`SectionCd`/`SectionTypeCd`は地域によってコードが違うので個別対応が必要
- [x] `L03-b-c`の`L03b_c_002`のコードリストは2つあるがかぶってなさそうなのでまとめてしまえる (<https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-L03-b-c.html>)
- [ ] `A19s`のコードリストは手動で生成: https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A19s.html
- [ ] `A20s`のコードリストは手動で生成: https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A20s.html
- [ ] `A21s`のコードリストは手動で生成: https://nlftp.mlit.go.jp/ksj/gml/datalist/KsjTmplt-A21s.html
- [ ] proj の補完 https://nlftp.mlit.go.jp/ksj/other/manual.html
